export { default as UIButtonBase } from "./UIButtonBase/UIButtonBase.vue";
export { default as UITabsBase } from "./UITabsBase/UITabsBase.vue";
export { default as UIInputBase } from "./inputs/UIInputBase/UIInputBase.vue";
export { default as UISearchInput } from "./inputs/UISearchInput/UISearchInput.vue";
export { default as UIAvatarBase } from "./UIAvatarBase/UIAvatarBase.vue";
export { default as UILoaderBase } from "./loaders/UILoaderBase/UILoaderBase.vue";
export { default as UILoaderLayout } from "./loaders/UILoaderLayout/UILoaderLayout.vue";
export { default as UITextareaBase } from "./UITextareaBase/UITextareaBase.vue";
export { default as UIInputNumber } from "./inputs/UIInputNumber/UIInputNumber.vue";
